import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";
// Importar el componente del banner de cookies
import CookieConsentBanner from "@/components/core/CookieConsentBanner"; 

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio LSCF",
  description: "Generated by LSCF",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={bricolageGrotesque.className}>
        <Header />
        {children}
        <Footer/>
        {/* Colocar el banner aquí para que aparezca en todas las páginas */}
        <CookieConsentBanner /> 
      </body>
    </html>
  );
}
